# netlify.toml - Configuration for Netlify deployment

[build]
  # The directory containing the source code (relative to the repository root)
  base = "src/web"
  
  # The directory to publish (relative to the base directory)
  publish = "dist"
  
  # The build command
  command = "npm run build"
  
  # Build environment variables
  [build.environment]
    NODE_VERSION = "16"
    NPM_VERSION = "7"

# Production context: All deploys from the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]
    VITE_API_BASE_URL = "https://api.parkhub.com"
    VITE_API_LANDMARK_ID = "7fc72127-c601-46f3-849b-0fdea9f370ae"
    VITE_ENABLE_DEBUG_LOGGING = "false"
    VITE_ENABLE_MOCK_API = "false"

# Staging context: All deploys from the staging branch
# will inherit these settings
[context.staging]
  [context.staging.environment]
    VITE_API_BASE_URL = "https://api-staging.parkhub.com"
    VITE_API_LANDMARK_ID = "7fc72127-c601-46f3-849b-0fdea9f370ae"
    VITE_ENABLE_DEBUG_LOGGING = "true"
    VITE_ENABLE_MOCK_API = "false"

# Development context: All deploys from the development branch
# will inherit these settings
[context.development]
  [context.development.environment]
    VITE_API_BASE_URL = "https://api-dev.parkhub.com"
    VITE_API_LANDMARK_ID = "7fc72127-c601-46f3-849b-0fdea9f370ae"
    VITE_ENABLE_DEBUG_LOGGING = "true"
    VITE_ENABLE_MOCK_API = "true"

# Branch deploy context: All deploys that are not from
# a pull/merge request or from the production, staging,
# or development branches will inherit these settings.
[context.branch-deploy]
  [context.branch-deploy.environment]
    VITE_API_BASE_URL = "https://api-dev.parkhub.com"
    VITE_API_LANDMARK_ID = "7fc72127-c601-46f3-849b-0fdea9f370ae"
    VITE_ENABLE_DEBUG_LOGGING = "true"
    VITE_ENABLE_MOCK_API = "true"

# Deploy preview context: All deploys resulting from a pull/merge request
# will inherit these settings.
[context.deploy-preview]
  [context.deploy-preview.environment]
    VITE_API_BASE_URL = "https://api-dev.parkhub.com"
    VITE_API_LANDMARK_ID = "7fc72127-c601-46f3-849b-0fdea9f370ae"
    VITE_ENABLE_DEBUG_LOGGING = "true"
    VITE_ENABLE_MOCK_API = "true"

# Redirect rule for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  [redirects.conditions]
    Language = ["en"]
    Country = ["US"]

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.parkhub.com https://api-staging.parkhub.com https://api-dev.parkhub.com; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; font-src 'self'; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests; block-all-mixed-content"
    
# Caching headers for JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Caching headers for CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Caching headers for asset files
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Lighthouse plugin for performance monitoring
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "lighthouse-results"
    [plugins.inputs.fail_deploy_on_score_thresholds]
      performance = 70
      accessibility = 90
      best-practices = 80
      seo = 80