name: Lint

on:
  push:
    branches: [main]
    paths:
      - 'src/web/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/web/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'src/web/package-lock.json'
          
      - name: Install dependencies
        working-directory: src/web
        run: npm ci
        
      - name: Run ESLint
        working-directory: src/web
        run: npm run lint
        
      - name: Check formatting with Prettier
        working-directory: src/web
        run: npx prettier --check "src/**/*.{ts,tsx,css}"
        
      - name: Run TypeScript type checking
        working-directory: src/web
        run: npm run typecheck

  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'src/web/package-lock.json'
          
      - name: Install dependencies
        working-directory: src/web
        run: npm ci
        
      - name: Run npm audit
        working-directory: src/web
        run: npm audit --production

  summary:
    name: Lint Summary
    runs-on: ubuntu-latest
    needs: [lint, security_scan]
    if: always()
    steps:
      - name: Summarize lint results
        run: echo "Linting and security scanning completed at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"